import { describe, expect, test } from 'bun:test'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { CreateTableInput } from '@anko/desktop-domain'
import { buildCreateTableSql } from '../create-table'
import { SqliteConnector } from '../sqlite'

const base: Omit<CreateTableInput, 'connectionId'> = {
  database: 'app',
  schema: 'public',
  tableName: 'users',
  columns: [
    {
      name: 'id',
      dataType: 'INTEGER',
      nullable: false,
      primaryKey: true,
      autoIncrement: true,
    },
    {
      name: 'display_name',
      dataType: 'TEXT',
      nullable: false,
      primaryKey: false,
      autoIncrement: false,
    },
  ],
}

describe('buildCreateTableSql', () => {
  test('builds PostgreSQL identity columns in the selected schema', () => {
    expect(buildCreateTableSql('postgresql', base).sql).toBe(
      'CREATE TABLE "public"."users" (\n' +
        '  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n' +
        '  "display_name" TEXT NOT NULL,\n' +
        '  PRIMARY KEY ("id")\n' +
        ');',
    )
  })

  test('builds qualified MySQL tables with auto increment', () => {
    const input = {
      ...base,
      columns: base.columns.map((column) => ({
        ...column,
        dataType: column.name === 'id' ? 'BIGINT' : 'VARCHAR(255)',
      })),
    }
    expect(buildCreateTableSql('mysql', input).sql).toContain('`id` BIGINT NOT NULL AUTO_INCREMENT')
    expect(buildCreateTableSql('mysql', input).sql).toStartWith('CREATE TABLE `app`.`users`')
  })

  test('uses SQLite inline autoincrement primary keys', () => {
    expect(buildCreateTableSql('sqlite', base).sql).toContain(
      '"id" INTEGER PRIMARY KEY AUTOINCREMENT',
    )
    expect(buildCreateTableSql('sqlite', base).sql).not.toContain('PRIMARY KEY (')
  })

  test('quotes embedded identifier delimiters', () => {
    expect(buildCreateTableSql('postgresql', { ...base, tableName: 'odd"table' }).sql).toStartWith(
      'CREATE TABLE "public"."odd""table"',
    )
  })

  test('rejects duplicate columns and unsupported types', () => {
    expect(() =>
      buildCreateTableSql('postgresql', {
        ...base,
        columns: [base.columns[0]!, { ...base.columns[0]!, name: 'ID' }],
      }),
    ).toThrow('Duplicate column name')
    expect(() =>
      buildCreateTableSql('postgresql', {
        ...base,
        columns: [{ ...base.columns[0]!, dataType: 'DROP TABLE users' }],
      }),
    ).toThrow('Unsupported postgresql data type')
  })

  test('rejects invalid auto-increment combinations', () => {
    expect(() =>
      buildCreateTableSql('postgresql', {
        ...base,
        columns: [{ ...base.columns[0]!, dataType: 'TEXT' }],
      }),
    ).toThrow('Auto increment is not supported')
    expect(() =>
      buildCreateTableSql('postgresql', {
        ...base,
        columns: [base.columns[0]!, { ...base.columns[1]!, primaryKey: true }],
      }),
    ).toThrow('only primary key')
  })

  test('creates a table through the SQLite connector', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'anko-create-table-'))
    const connector = await SqliteConnector.connect({
      name: 'Create table test',
      host: join(directory, 'test.sqlite'),
      port: 0,
      username: '',
      password: '',
      driver: 'sqlite',
    })
    try {
      const { sql } = buildCreateTableSql('sqlite', base)
      await connector.executeWithContext(sql, 'main')
      expect(await connector.getTables('main', '')).toContainEqual(
        expect.objectContaining({ name: 'users', table_type: 'BASE TABLE' }),
      )
      expect(await connector.getColumns('main', '', 'users')).toEqual([
        expect.objectContaining({ name: 'id', key: 'PRI', data_type: 'integer' }),
        expect.objectContaining({ name: 'display_name', nullable: false, data_type: 'text' }),
      ])
    } finally {
      await connector.close()
    }
  })
})
