// Database initialization

// Schema & entities
export type { DrizzleDB } from './client'
export { initializeDb } from './client'
export * from './entities'
export { addQueryHistory } from './mutations/add-query-history'
export { addWorkspaceConnection } from './mutations/add-workspace-connection'
export { clearConnections } from './mutations/clear-connections'
export { clearQueryHistory } from './mutations/clear-query-history'
export { clearSavedQueries } from './mutations/clear-saved-queries'
export { clearWorkspaces } from './mutations/clear-workspaces'
export { createSavedQuery } from './mutations/create-saved-query'
export { createWorkspace } from './mutations/create-workspace'
export { deleteConnection } from './mutations/delete-connection'
export { deleteQueryHistory } from './mutations/delete-query-history'
export { deleteSavedQuery } from './mutations/delete-saved-query'
export { deleteWorkspace } from './mutations/delete-workspace'
export { moveWorkspaceConnection } from './mutations/move-workspace-connection'
export { removeConnectionFromAllWorkspaces } from './mutations/remove-connection-from-all-workspaces'
export { removeWorkspaceConnection } from './mutations/remove-workspace-connection'
// Mutations
export { saveConnection } from './mutations/save-connection'
export { saveWindowState } from './mutations/save-window-state'
export { saveWorkspaceSession } from './mutations/save-workspace-session'
export { setAppMeta } from './mutations/set-app-meta'
export { updateConnection } from './mutations/update-connection'
export { updateSavedQuery } from './mutations/update-saved-query'
export { updateWorkspace } from './mutations/update-workspace'
export { getAppMeta } from './queries/get-app-meta'
// Queries
export { getConnection } from './queries/get-connection'
export { getConnectionConfig } from './queries/get-connection-config'
export { getQueryHistoryEntry } from './queries/get-query-history-entry'
export { getSavedQueryById } from './queries/get-saved-query'
export { getWindowState } from './queries/get-window-state'
export { getWorkspaceById } from './queries/get-workspace'
export { getWorkspaceConnections } from './queries/get-workspace-connections'
export { getWorkspaceSession } from './queries/get-workspace-session'
export { listConnections } from './queries/list-connections'
export { listQueryHistory } from './queries/list-query-history'
export { listSavedQueries } from './queries/list-saved-queries'
export { listWorkspaces } from './queries/list-workspaces'
