// Storage (local persistence)
export type { DrizzleDB } from './storage/client'
export { initializeDb } from './storage/client'
export { addQueryHistory } from './storage/mutations/add-query-history'
export { addWorkspaceConnection } from './storage/mutations/add-workspace-connection'
export { clearConnections } from './storage/mutations/clear-connections'
export { clearQueryHistory } from './storage/mutations/clear-query-history'
export { clearSavedQueries } from './storage/mutations/clear-saved-queries'
export { clearWorkspaces } from './storage/mutations/clear-workspaces'
export { createSavedQuery } from './storage/mutations/create-saved-query'
export { createWorkspace } from './storage/mutations/create-workspace'
export { deleteConnection } from './storage/mutations/delete-connection'
export { deleteQueryHistory } from './storage/mutations/delete-query-history'
export { deleteSavedQuery } from './storage/mutations/delete-saved-query'
export { deleteWorkspace } from './storage/mutations/delete-workspace'
export { moveWorkspaceConnection } from './storage/mutations/move-workspace-connection'
export { removeConnectionFromAllWorkspaces } from './storage/mutations/remove-connection-from-all-workspaces'
export { removeWorkspaceConnection } from './storage/mutations/remove-workspace-connection'
export { saveConnection } from './storage/mutations/save-connection'
export { saveWindowState } from './storage/mutations/save-window-state'
export { saveWorkspaceSession } from './storage/mutations/save-workspace-session'
export { setAppMeta } from './storage/mutations/set-app-meta'
export { updateConnection } from './storage/mutations/update-connection'
export { updateSavedQuery } from './storage/mutations/update-saved-query'
export { updateWorkspace } from './storage/mutations/update-workspace'
export { getAppMeta } from './storage/queries/get-app-meta'
export { getConnection } from './storage/queries/get-connection'
export { getConnectionConfig } from './storage/queries/get-connection-config'
export { getQueryHistoryEntry } from './storage/queries/get-query-history-entry'
export { getSavedQueryById } from './storage/queries/get-saved-query'
export { getWindowState } from './storage/queries/get-window-state'
export { getWorkspaceById } from './storage/queries/get-workspace'
export { getWorkspaceConnections } from './storage/queries/get-workspace-connections'
export { getWorkspaceSession } from './storage/queries/get-workspace-session'
export { listConnections } from './storage/queries/list-connections'
export { listQueryHistory } from './storage/queries/list-query-history'
export { listSavedQueries } from './storage/queries/list-saved-queries'
export { listWorkspaces } from './storage/queries/list-workspaces'

// Database connectors
export type { DatabaseConnector } from './db/connector'
export { buildCreateTableSql } from './db/create-table'
export { MySqlConnector } from './db/mysql'
export { PostgresConnector } from './db/postgres'
export { SqliteConnector } from './db/sqlite'
