import {
  CREATE_TABLE_DATA_TYPES,
  type CreateTableColumnInput,
  type CreateTableDriver,
  type CreateTableInput,
  supportsAutoIncrement,
} from '@anko/desktop-domain'
import { AppError } from '@anko/desktop-domain'

const MAX_IDENTIFIER_LENGTH = 128
const MAX_COLUMNS = 100

export function buildCreateTableSql(
  driver: CreateTableDriver,
  input: Omit<CreateTableInput, 'connectionId'>,
): { sql: string; tableName: string } {
  const tableName = validateIdentifier(input.tableName, 'Table name')
  const database = validateIdentifier(input.database, 'Database')
  const schema =
    driver === 'postgresql' ? validateIdentifier(input.schema || 'public', 'Schema') : undefined

  if (input.columns.length === 0) throw AppError.validation('Add at least one column')
  if (input.columns.length > MAX_COLUMNS) {
    throw AppError.validation(`Tables can contain at most ${MAX_COLUMNS} columns`)
  }

  const columns = input.columns.map((column) => normalizeColumn(driver, column))
  const names = new Set<string>()
  for (const column of columns) {
    const key = column.name.toLocaleLowerCase()
    if (names.has(key)) throw AppError.validation(`Duplicate column name: ${column.name}`)
    names.add(key)
  }

  const primaryKeys = columns.filter((column) => column.primaryKey)
  const autoIncrement = columns.filter((column) => column.autoIncrement)
  if (autoIncrement.length > 1) {
    throw AppError.validation('Only one column can use auto increment')
  }
  if (autoIncrement.length === 1 && primaryKeys.length !== 1) {
    throw AppError.validation('An auto-increment column must be the only primary key')
  }

  const definitions = columns.map((column) => columnDefinition(driver, column))
  const sqliteInlinePrimaryKey = driver === 'sqlite' && autoIncrement.length === 1
  if (primaryKeys.length > 0 && !sqliteInlinePrimaryKey) {
    definitions.push(
      `PRIMARY KEY (${primaryKeys.map((column) => quoteIdentifier(column.name, driver)).join(', ')})`,
    )
  }

  const tableRef =
    driver === 'postgresql'
      ? `${quoteIdentifier(schema!, driver)}.${quoteIdentifier(tableName, driver)}`
      : driver === 'mysql'
        ? `${quoteIdentifier(database, driver)}.${quoteIdentifier(tableName, driver)}`
        : quoteIdentifier(tableName, driver)

  return {
    tableName,
    sql: `CREATE TABLE ${tableRef} (\n  ${definitions.join(',\n  ')}\n);`,
  }
}

function normalizeColumn(
  driver: CreateTableDriver,
  column: CreateTableColumnInput,
): CreateTableColumnInput {
  const name = validateIdentifier(column.name, 'Column name')
  const dataType = column.dataType.trim().toUpperCase()
  if (!CREATE_TABLE_DATA_TYPES[driver].includes(dataType)) {
    throw AppError.validation(`Unsupported ${driver} data type: ${column.dataType}`)
  }
  if (column.autoIncrement && !supportsAutoIncrement(driver, dataType)) {
    throw AppError.validation(`Auto increment is not supported for ${dataType}`)
  }
  if (column.autoIncrement && !column.primaryKey) {
    throw AppError.validation('Auto-increment columns must be primary keys')
  }

  return {
    name,
    dataType,
    nullable: column.primaryKey ? false : column.nullable,
    primaryKey: column.primaryKey,
    autoIncrement: column.autoIncrement,
  }
}

function columnDefinition(driver: CreateTableDriver, column: CreateTableColumnInput): string {
  const identifier = quoteIdentifier(column.name, driver)
  if (driver === 'sqlite' && column.autoIncrement) {
    return `${identifier} INTEGER PRIMARY KEY AUTOINCREMENT`
  }

  const parts = [identifier, column.dataType]
  if (!column.nullable) parts.push('NOT NULL')
  if (column.autoIncrement) {
    parts.push(driver === 'postgresql' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT')
  }
  return parts.join(' ')
}

function validateIdentifier(value: string, label: string): string {
  const normalized = value.trim()
  if (!normalized) throw AppError.validation(`${label} is required`)
  if (normalized.length > MAX_IDENTIFIER_LENGTH) {
    throw AppError.validation(`${label} must be ${MAX_IDENTIFIER_LENGTH} characters or fewer`)
  }
  if (/\p{Cc}/u.test(normalized)) {
    throw AppError.validation(`${label} cannot contain control characters`)
  }
  return normalized
}

function quoteIdentifier(identifier: string, driver: CreateTableDriver): string {
  if (driver === 'mysql') return `\`${identifier.replace(/`/g, '``')}\``
  return `"${identifier.replace(/"/g, '""')}"`
}
