import type { SqlKeyword } from '../types'

export const SQL_KEYWORDS_WITH_INFO: SqlKeyword[] = [
  // Data Query Language (DQL)
  { name: 'SELECT', category: 'DQL' },
  { name: 'FROM', category: 'DQL' },
  { name: 'WHERE', category: 'DQL' },
  { name: 'AND', category: 'operator' },
  { name: 'OR', category: 'operator' },
  { name: 'NOT', category: 'operator' },
  { name: 'IN', category: 'operator' },
  { name: 'BETWEEN', category: 'operator' },
  { name: 'LIKE', category: 'operator' },
  { name: 'IS', category: 'operator' },
  { name: 'NULL', category: 'clause' },
  { name: 'AS', category: 'clause' },
  { name: 'DISTINCT', category: 'DQL' },
  { name: 'ALL', category: 'DQL' },
  { name: 'ORDER', category: 'DQL' },
  { name: 'BY', category: 'clause' },
  { name: 'ASC', category: 'clause' },
  { name: 'DESC', category: 'clause' },
  { name: 'LIMIT', category: 'DQL' },
  { name: 'OFFSET', category: 'DQL' },
  { name: 'GROUP', category: 'DQL' },
  { name: 'HAVING', category: 'DQL' },
  { name: 'UNION', category: 'DQL' },
  { name: 'INTERSECT', category: 'DQL' },
  { name: 'EXCEPT', category: 'DQL' },
  { name: 'JOIN', category: 'DQL' },
  { name: 'INNER', category: 'DQL' },
  { name: 'LEFT', category: 'DQL' },
  { name: 'RIGHT', category: 'DQL' },
  { name: 'FULL', category: 'DQL' },
  { name: 'OUTER', category: 'DQL' },
  { name: 'CROSS', category: 'DQL' },
  { name: 'ON', category: 'clause' },
  { name: 'USING', category: 'clause' },
  { name: 'NATURAL', category: 'DQL' },
  { name: 'EXISTS', category: 'operator' },
  { name: 'ANY', category: 'operator' },
  { name: 'SOME', category: 'operator' },

  // Data Manipulation Language (DML)
  { name: 'INSERT', category: 'DML' },
  { name: 'INTO', category: 'DML' },
  { name: 'VALUES', category: 'DML' },
  { name: 'UPDATE', category: 'DML' },
  { name: 'SET', category: 'DML' },
  { name: 'DELETE', category: 'DML' },
  { name: 'TRUNCATE', category: 'DML' },
  { name: 'MERGE', category: 'DML' },

  // Data Definition Language (DDL)
  { name: 'CREATE', category: 'DDL' },
  { name: 'ALTER', category: 'DDL' },
  { name: 'DROP', category: 'DDL' },
  { name: 'TABLE', category: 'DDL' },
  { name: 'DATABASE', category: 'DDL' },
  { name: 'SCHEMA', category: 'DDL' },
  { name: 'INDEX', category: 'DDL' },
  { name: 'VIEW', category: 'DDL' },
  { name: 'CONSTRAINT', category: 'DDL' },
  { name: 'PRIMARY', category: 'DDL' },
  { name: 'KEY', category: 'DDL' },
  { name: 'FOREIGN', category: 'DDL' },
  { name: 'REFERENCES', category: 'DDL' },
  { name: 'UNIQUE', category: 'DDL' },
  { name: 'CHECK', category: 'DDL' },
  { name: 'DEFAULT', category: 'DDL' },
  { name: 'AUTO_INCREMENT', category: 'DDL' },
  { name: 'SERIAL', category: 'DDL' },
  { name: 'IDENTITY', category: 'DDL' },
  { name: 'CASCADE', category: 'DDL' },
  { name: 'RESTRICT', category: 'DDL' },

  // Data Control Language (DCL)
  { name: 'GRANT', category: 'DCL' },
  { name: 'REVOKE', category: 'DCL' },
  { name: 'PRIVILEGES', category: 'DCL' },
  { name: 'TO', category: 'clause' },
  { name: 'WITH', category: 'clause' },
  { name: 'OPTION', category: 'clause' },

  // Transaction Control Language (TCL)
  { name: 'BEGIN', category: 'TCL' },
  { name: 'COMMIT', category: 'TCL' },
  { name: 'ROLLBACK', category: 'TCL' },
  { name: 'SAVEPOINT', category: 'TCL' },
  { name: 'TRANSACTION', category: 'TCL' },
  { name: 'START', category: 'TCL' },

  // Data types
  { name: 'INT', category: 'type' },
  { name: 'INTEGER', category: 'type' },
  { name: 'BIGINT', category: 'type' },
  { name: 'SMALLINT', category: 'type' },
  { name: 'TINYINT', category: 'type' },
  { name: 'DECIMAL', category: 'type' },
  { name: 'NUMERIC', category: 'type' },
  { name: 'FLOAT', category: 'type' },
  { name: 'DOUBLE', category: 'type' },
  { name: 'REAL', category: 'type' },
  { name: 'BOOLEAN', category: 'type' },
  { name: 'BOOL', category: 'type' },
  { name: 'CHAR', category: 'type' },
  { name: 'VARCHAR', category: 'type' },
  { name: 'TEXT', category: 'type' },
  { name: 'BLOB', category: 'type' },
  { name: 'DATE', category: 'type' },
  { name: 'TIME', category: 'type' },
  { name: 'DATETIME', category: 'type' },
  { name: 'TIMESTAMP', category: 'type' },
  { name: 'YEAR', category: 'type' },
  { name: 'JSON', category: 'type' },
  { name: 'UUID', category: 'type' },
  { name: 'BIGSERIAL', category: 'type' },

  // Common clauses
  { name: 'IF', category: 'clause' },
  { name: 'ELSE', category: 'clause' },
  { name: 'THEN', category: 'clause' },
  { name: 'END', category: 'clause' },
  { name: 'CASE', category: 'clause' },
  { name: 'WHEN', category: 'clause' },
  { name: 'COALESCE', category: 'clause' },
  { name: 'NULLIF', category: 'clause' },
  { name: 'CAST', category: 'clause' },
  { name: 'CONVERT', category: 'clause' },
  { name: 'OVER', category: 'clause' },
  { name: 'PARTITION', category: 'clause' },
  { name: 'WINDOW', category: 'clause' },
  { name: 'ROW', category: 'clause' },
  { name: 'ROWS', category: 'clause' },
  { name: 'RANGE', category: 'clause' },
  { name: 'UNBOUNDED', category: 'clause' },
  { name: 'PRECEDING', category: 'clause' },
  { name: 'FOLLOWING', category: 'clause' },
  { name: 'CURRENT', category: 'clause' },

  // MySQL specific
  { name: 'ENGINE', category: 'DDL' },
  { name: 'CHARSET', category: 'DDL' },
  { name: 'COLLATE', category: 'DDL' },
  { name: 'UNSIGNED', category: 'type' },
  { name: 'ZEROFILL', category: 'type' },
  { name: 'REPLACE', category: 'DML' },
  { name: 'IGNORE', category: 'clause' },
  { name: 'DELAYED', category: 'clause' },
  { name: 'LOW_PRIORITY', category: 'clause' },
  { name: 'HIGH_PRIORITY', category: 'clause' },
  { name: 'STRAIGHT_JOIN', category: 'DQL' },
  { name: 'SQL_CALC_FOUND_ROWS', category: 'DQL' },
  { name: 'FORCE', category: 'clause' },
  { name: 'USE', category: 'clause' },
  { name: 'EXPLAIN', category: 'DQL' },
  { name: 'ANALYZE', category: 'DQL' },

  // PostgreSQL specific
  { name: 'RETURNING', category: 'DQL' },
  { name: 'ILIKE', category: 'operator' },
  { name: 'SIMILAR', category: 'operator' },
  { name: 'ARRAY', category: 'type' },
  { name: 'VARIADIC', category: 'clause' },
  { name: 'LATERAL', category: 'DQL' },
  { name: 'RECURSIVE', category: 'DQL' },
  { name: 'MATERIALIZED', category: 'DDL' },
  { name: 'CONCURRENTLY', category: 'DDL' },
  { name: 'TABLESPACE', category: 'DDL' },
  { name: 'EXTENSION', category: 'DDL' },
  { name: 'SEQUENCE', category: 'DDL' },
  { name: 'GENERATED', category: 'DDL' },
  { name: 'ALWAYS', category: 'clause' },
  { name: 'STORED', category: 'DDL' },
  { name: 'INCLUDE', category: 'clause' },
  { name: 'NULLS', category: 'clause' },
  { name: 'FIRST', category: 'clause' },
  { name: 'LAST', category: 'clause' },
]

// Backward compatible export (array of just names)
export const SQL_KEYWORDS = SQL_KEYWORDS_WITH_INFO.map((k) => k.name)
